### ISSUE TITLE
"Undefined property: Illuminate\Database\Query\Builder::$expressions"

### ISSUE THREAD

**Issue by ashishnimrot** [staudenmeir/laravel-cte#2]
public function compileExpressions(Builder $query)
    {
        if (! $query->expressions) {
            return '';
        }
 
        $recursive = $this->recursiveKeyword($query->expressions);
 
        $statements = [];
 
        foreach ($query->expressions as $expression) {
            $columns = $expression['columns'] ? '('.$this->columnize($expression['columns']).') ' : '';
 
            $statements[] = $this->wrap($expression['name']).' '.$columns.'as ('.$expression['query'].')';
        }
 
        return 'with '.$recursive.implode($statements, ', ');
    }
 
    /**
     * Get the "recursive" keyword.
     *
     * @param  array  $expressions
Arguments
"Undefined property: Illuminate\Database\Query\Builder::$expressions"

**Comment by staudenmeir** [comment]
What does the query look like that causes this error?

**Comment by quarkmarino** [comment]
Ok, this is the issue I'm having too, when I add the trait

```php
use QueriesExpressions;
```
to a single model, and instantiate that model and only that model, everything works nice, but, when I instantiate another model that doesn't need the trait in any way, I got the same "Undefined Property" error.

Now, all my models extends from a custom BaseModel class, and when I try to make it to use the trait in order to give it to every model

```php
use Illuminate\Database\Eloquent\Model;
use Staudenmeir\LaravelCte\Eloquent\QueriesExpressions;

class BaseModel extends Model {
  use QueriesExpressions
  ...
}
```
I get another type of error 

```
Trait method newBaseQueryBuilder has not been applied, because there are collisions with other trait methods on App\Suits\Base\BaseModel
```
I'm trying to rename the method or using the "insteadof" operator, but haven't figured out exactly how to solve it.

Thank you.

**Comment by staudenmeir** [comment]
The latest release fixes this issue.

@quarkmarino You are getting the "Trait method newBaseQueryBuilder has not been applied" error because there already is a `newBaseQueryBuilder()` method in `BaseModel`. It is from a different package?

**Comment by quarkmarino** [comment]
I can find 1 class and 2 traits in my project that defines some type of newBaseQueryBuilder():

the laravel model class
Illuminate\Database\Eloquent\Model;

watson/rememberable trait
Watson\Rememberable\Rememberable;

and yours 
Staudenmeir\LaravelCte\Eloquent\QueriesExpressions;

I guess I'll have to disable the rememberable trait until I really need it again, and try to fix from that side when enabling it again.

Thank you.

**Comment by staudenmeir** [comment]
Yes, you can only use one of these traits at the same time.
